### ISSUE TITLE
feed link is not correct

### ISSUE THREAD

**Issue by hdhoang** [jmmv/jmmv.dev#1] opened 2020-10-12 01:47 UTC
https://github.com/jmmv/jmmv.dev/blob/c5177f3bb30a7ba008ef4d098ca1e6600321969f/index.html#L29-L30
 this link is 404 now.

`/feeds/posts/default` like blogger works, with https://github.com/jmmv/jmmv.dev/blob/master/feeds/posts/default.

Please try adding an alias, thanks. Good luck on your new endeavours.

**Comment by jmmv** [comment] 2020-10-12 14:58
This was caused by me trying to fix how the feeds were generated a few days ago... and messing things up. The `feed.xml` is now fixed.

But I've also replaced the old `feeds/posts/default` with a manual XML redirect. Not sure yet if this is going to do the right thing.

**Closed by jmmv** 2020-10-12 14:58 UTC
